[pytest]
django_find_project = false
pythonpath = ./tests/demo/ ./src
DJANGO_SETTINGS_MODULE = demoapp.settings
norecursedirs = "demo", ".tox"
addopts =
    --tb=short
    --capture=no
    --echo-version=django
    --echo-attr=django.conf.settings.DATABASES.default.ENGINE
    --cov=admin_sync
    --cov-report=html
    --cov-report=xml
    --cov-config=tests/.coveragerc

markers =
    functional: mark a test as functional
    selenium: selenium test
    skip: skip test
