name: Test

on:
    push:
        branches:
            - master
            - develop
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            # You can use PyPy versions in python-version.
            # For example, pypy-2.7 and pypy-3.8
            matrix:
                python-version: ["3.9"]
        steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-python@v2

        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip flake8 isort tox
        -   name: Lint with flake8
            run: |
                tox -e lint

    test:
        #        if: ${{github.event}} && ${{ !contains(github.event.head_commit.message, 'ci skip') }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: [ "3.9", "3.10"]
                django-version: [ "2.2", "3.2", "4.0", "4.1" ]
        env:
            PY_VER: ${{ matrix.python-version}}
            DJ_VER: ${{ matrix.django-version}}

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install dependencies
                run: python -m pip install tox

            -   name: Test with Tox
                run: tox -e d${DJ_VER//.}-py${PY_VER//.} -- --create-db --cov-report=xml --cov-report=term --junitxml=pytest.xml

            -   uses: codecov/codecov-action@v1
                with:
#                    files: ./coverage1.xml,./coverage2.xml # optional
#                    flags: unittests # optional
#                    name: codecov-umbrella # optional
#                    fail_ci_if_error: true # optional (default = false)
                    verbose: true # optional (default = false)
